-----CASES-----
/* SYNTAX OF CASE IN SQL
SELECT COLUMN1,
CASE
WHEN (CONDITION1) THEN RESULT1
WHEN (CONDITION2) THEN RESULT2
....
ELSE DEFAULT_RESULT
END AS NEW_COLUMN_NAME
FROM TABLE_NAME; */

/* 
Best way to learn the case is using a simple example where you will add a custom column in which you will have price_tag.
If the price is above 1000 you will say it is expensive.
If the price is between 500 and 1000 you will say it is moderate.
And if the price is below 500 it is cheap.
*/

SELECT * FROM PRODUCTS; --TO SHOWCASE THE TABLE

SELECT NAME , PRICE ,
CASE WHEN (PRICE > 1000) THEN 'Expensive'
     WHEN (PRICE BETWEEN 500 AND 1000) THEN 'Moderate'
	 ELSE 'Cheap'
END AS PRICE_TAG FROM PRODUCTS;

--NOTE : THIS IS ONLY THE SNAPSHOT OF THE TABLE , THIS IS NOT REAL TABLE 
-- TO USE THIS INTO REAL TABLE WE'LL USE ALTER COMMAND

--STEPS TO ALTER THIS DATA INTO REAL TABLE
--STEP-1 : CREATE A NEW COLUMN
ALTER TABLE PRODUCTS ADD COLUMN PRICE_TAGE TEXT;
--STEP-2 : UPDATE THAT COLUMN USING CASE
UPDATE PRODUCTS 
SET PRICE_TAGE = 
CASE WHEN PRICE > 1000 THEN 'Expensive'
     WHEN PRICE BETWEEN 500 AND 1000 THEN 'Moderate'
	 ELSE 'CHEAP'
END;
SELECT * FROM PRODUCTS;

-- SECOND EXAMPLE
SELECT NAME , 
CASE WHEN IS_AVAILABLE THEN 'IN STOCK'
ELSE 'OUT OF STOCK'
END AS AVAILABILITY_STATUS
FROM PRODUCTS;

--PRACTICE-2 HIGHLIGHT STOCK STATUS
/* SHOW PRODUCT NAME , STOCK QUANTITY AND LABEL:"
1. 'HIGH STOCK' IF QUANTITY > 100
2. 'MEDIUM STOCK' IF BETWEEN 30 AND 100
3. 'LOW STOCK' OTHERWISE */
SELECT NAME , STOCK_QUANTITY ,
CASE WHEN STOCK_QUANTITY > 100 THEN 'HIGH STOCK'
     WHEN STOCK_QUANTITY BETWEEN 30 AND 100 THEN 'MEDIUM STOCK'
	 ELSE 'LOW STOCK'
END AS STOCK_LABEL
FROM PRODUCTS;






